### ISSUE TITLE
No prompt on device...

### ISSUE THREAD

**Issue by leobergamo** [MeisApps/pcbu-natives#1]
Hello,

I've recently installed your app on phone and Linux.  Everything went accordingly but when using sudo for instance; I am prompted to use phone but phone never prompts for fingerprint.  The phone is a Samsung Galaxy Ultra S22 running Android 13.
Please advise...

Regards

**Comment by MeisApps** [comment]
Hi,

this is usually caused by the android phone killing PC Bio Unlock's background service to save battery.
Please try disabling battery optimizations for the app.

1. Go to the app on your home/app screen and hold the icon.
2. Select the info icon on the popup window.
3. Select "Battery".
4. Check "Don't optimize".

After that open the app and try again.
Hope this helps.

Best regards,
Meis Apps

**Comment by leobergamo** [comment]
No change

**Comment by MeisApps** [comment]
Hi,

to assist you further, I need more information about your setup.

- What Linux Distribution are you using?
- Did you choose TCP or Bluetooth during the pairing process.
- Is there any error message when using sudo or does it just wait for a connection?

Finally, it would be greatly appreciated if you could provide me with the contents of the log file located at /etc/pc-bio-unlock/module.log.

Best regards,
Meis Apps
